bag/urls.py
"""Urls for bag app"""
from django.urls import path
from bag import views


app_name = 'bag'
urlpatterns = [
    path('', views.ViewBag.as_view(), name='view_bag'),
    path('add/<int:item_id>/', views.add_to_bag, name='add_to_bag'),
    path('adjust/<int:item_id>/', views.adjust_bag, name='adjust_bag'),
    path('remove_item/<int:item_id>/', views.remove_item, name='remove_item'),
]

green_bean/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('profile/', include('profiles.urls')),
    path('bag/', include('bag.urls')),
    path('checkout/', include('checkout.urls')),
    path('robots.txt', TemplateView.as_view(
        template_name="robots.txt", content_type="text/plain"),
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'home.views.error_404'
handler500 = 'home.views.error_500'

products/urls.py
"""Urls for products app"""
from django.urls import path
from products import views

app_name = 'products'
urlpatterns = [
    path('', views.ProductListView.as_view(), name='products'),
    path('product_details/<int:pk>/', views.ProductDetailView.as_view(),
         name='product_details'),
    path('add/', views.CreateProductView.as_view(), name='add_product'),
    path('product_details/<int:pk>/update/', views.UpdateProductView.as_view(),
         name='edit_product'),
    path('product_details/<int:pk>/delete/', views.DeleteProductView.as_view(),
         name='delete_product'),
    path('product_details/<int:pk>/add_rating/', views.RateProduct.as_view(),
         name='add_rating'),
    # Type
    path('create_type/', views.CreateTypeView.as_view(),
         name='create_type'),
    path('add/add_type/', views.AddType.as_view(),
         name='add_type'),
    path('update_type/<int:pk>/', views.UpdateTypeView.as_view(),
         name='update_type'),
    path('delete_type/<int:pk>/', views.DeleteTypeView.as_view(),
         name='delete_type'),
    # Category
    path('create_category/', views.CreateCategoryView.as_view(),
         name='create_category'),
    path('add/add_category/', views.AddCategory.as_view(),
         name='add_category'),
    path('update_category/<int:pk>/', views.UpdateCategoryView.as_view(),
         name='update_category'),
    path('delete_category/<int:pk>/', views.DeleteCategoryView.as_view(),
         name='delete_category'),
    # Color
    path('create_color/', views.CreateColorView.as_view(),
         name='create_color'),
    path('add/add_color/', views.AddColor.as_view(),
         name='add_color'),
    path('update_color/<int:pk>/', views.UpdateColorView.as_view(),
         name='update_color'),
    path('delete_color/<int:pk>/', views.DeleteColorView.as_view(),
         name='delete_color'),
    # Size
    path('create_size/', views.CreateSizeView.as_view(),
         name='create_size'),
    path('add/add_size/', views.AddSize.as_view(),
         name='add_size'),
    path('update_size/<int:pk>/', views.UpdateSizeView.as_view(),
         name='update_size'),
    path('delete_size/<int:pk>/', views.DeleteSizeView.as_view(),
         name='delete_size'),

    path('manage_products', views.ManageProductsView.as_view(),
         name='manage_products')

]

products/models.py
"""Models for products app"""
import random
from django.contrib.auth.models import User
from django.db import models
from django.template.defaultfilters import slugify
from cloudinary.models import CloudinaryField


class Type(models.Model):
    """Create instance of Type"""
    product_type = models.CharField(max_length=100)
    type_code = models.CharField(max_length=5)
    slug = models. SlugField(max_length=100, unique=True)

    def save(self, *args, **kwargs):
        """
        Override the save method to set the product_type as slug
        """
        self.slug = slugify(self.product_type)
        super().save(*args, **kwargs)

    def __str__(self):
        """String method for type"""
        return self.product_type


class Size(models.Model):
    """Create instance of Size"""
    size_short = models.CharField(max_length=25)  # e.g. 'M'
    size_long = models.CharField(max_length=50)  # e.g. 'Medium'
    slug = models. SlugField(max_length=25, unique=True)

    def save(self, *args, **kwargs):
        """
        Override the save method to set the size_short as slug
        """
        self.slug = slugify(self.size_short)
        super().save(*args, **kwargs)

    def __str__(self):
        """String method for size"""
        return f'{self.size_long} ({self.size_short})'


class Color(models.Model):
    """Create instance of Color"""
    color = models.CharField(max_length=100)  # display color
    color_code = models.CharField(max_length=5)
    slug = models. SlugField(max_length=100, unique=True)

    def save(self, *args, **kwargs):
        """
        Override the save method to set the color as slug
        """
        self.slug = slugify(self.color)
        super().save(*args, **kwargs)

    def __str__(self):
        """String method for color"""
        return self.color


class Category(models.Model):
    """Create instance of Category"""
    category_name = models.CharField(max_length=200)
    friendly_name = models.CharField(max_length=254, null=True, blank=True)
    slug = models. SlugField(max_length=200, unique=True)

    def save(self, *args, **kwargs):
        """
        Override the save method to set the category_name as slug
        """
        self.slug = slugify(self.category_name)
        super().save(*args, **kwargs)

    class Meta:
        """Meta options for Product model"""
        verbose_name_plural = "categories"

    def get_friendly_name(self):
        """Friendly name for product category"""
        return self.friendly_name

    def __str__(self):
        """String method for category"""
        return self.category_name


class Product(models.Model):
    """Create product instance"""
    product_name = models.CharField(max_length=300)
    description = models.TextField()
    code = models.CharField(
            max_length=8,
            blank=True,
            editable=False,
            unique=True,
        )
    product_type = models.ForeignKey(
        Type, null=True, on_delete=models.SET_NULL)
    image = CloudinaryField('image', blank=True)
    category = models.ManyToManyField(Category, related_name='categories')
    size = models.ManyToManyField(Size, blank=True, related_name='sizes')
    color = models.ManyToManyField(Color, blank=True, related_name='colors')
    price = models.DecimalField(max_digits=6, decimal_places=2, null=True,
                                blank=True, default=00.00)

    def get_sizes(self):
        """Get all sizes for a product"""
        sizes = []
        for size in self.size.all():
            sizes.append(size)
        return sizes

    def get_colors(self):
        """Get all colors for a product"""
        colors = []
        for color in self.color.all():
            colors.append(color)
        return colors

    def get_categories(self):
        """Get list of categories for a product"""
        categories = []
        for category in self.category.all():
            categories.append(category)
        return categories

    def _generate_code(self):
        """Generate random number to use in the SKU and check for uniqueness"""
        code = random.randint(10000, 99999)
        products = Product.objects.all()
        codes = [product.code for product in products]

        while code in codes:
            new_code = random.randint(10000, 99999)
            code = new_code
            break
        return code

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the sku number
        if it hasn't been set already.
        """
        if not self.code:
            self.code = self._generate_code()
        super().save(*args, **kwargs)

    def __str__(self):
        """String method for product"""
        return self.product_name


class Rating(models.Model):
    """Create instance of rating"""
    RATING = (
        (1, 'Poor'),
        (2, 'Ok'),
        (3, 'Good'),
        (4, 'Very good'),
        (5, 'Excellent'),
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE,
                                related_name='rating')
    rating = models.IntegerField(default=0, choices=RATING)
    comment = models.TextField(max_length=1500)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """String method for rating"""
        return f'{self.product.product_name}_{self.rating}'

products/forms.py
"""Forms for Product view"""
from django import forms
from bootstrap_modal_forms.mixins import (
    PopRequestMixin,
    CreateUpdateAjaxMixin
)
from crispy_forms.helper import FormHelper
from crispy_forms.layout import (
    Layout,
    HTML,
    Field,
    Div,
    Row,
    Column
)
from .models import (
    Product,
    Category,
    Color,
    Type,
    Size,
    Rating,
)


class CreateProductForm(forms.ModelForm):
    """Form to create new product."""

    class Meta:
        """Meta class specifying fields."""
        model = Product
        exclude = ('slug',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        categories = Category.objects.all()
        friendly_names = [(c.id, c.get_friendly_name()) for c in categories]
        self.fields['category'].choices = friendly_names

        self.helper = FormHelper(self)
        self.helper.form_tag = False
        self.helper.disable_csrf = True
        self.helper.layout = Layout(
            Div('product_name', css_class="col-12 col-md-11 form-control\
                mb-3 bg-light"),
            Field('description', css_class="col-12 col-md-11\
                form-control mb-3 bg-light", rows="3", ),
            Div(Row(
                Column('product_type', css_class="col-12 col-md-11"),
                Column(HTML("""
                {% if not form.product_name.value %}
                    <div class="text-end"><span>
                    <a data-form-url="{% url 'products:add_type'%}"
                        class="create-new pointer" title="Add new product type"
                        aria-label="Add new product type">
                    <i class="fas fa-plus text-green pointer"></i></a>
                    </span></div>
                {% endif %}
                """),),
                ), css_class="form-control mb-3 bg-light",),
            Div(Row(
                Column('category', css_class='col-12 col-md-11'),
                Column(HTML("""
                    <div class="text-end">
                    <span class="clear_category text-green pointer"
                        title="Clear selection" aria-label="Clear selection">
                        <i class="fas fa-eraser"></i></span>
                    {% if not form.product_name.value %}<span>
                        <a data-form-url="{% url 'products:add_category'%}"
                        class="create-new text-green pointer"
                        title="Add new product
                        type" aria-label="Add new product type">
                        <i class="fas fa-plus"></i></a></span>
                    {% endif %}</div>
                """),),
                ), css_class="form-control mb-3 bg-light",),
            Div(Row(
                Column('color', css_class='col-12 col-md-11'),
                Column(HTML("""
                <div class="text-end">
                <span class="clear_color text-green pointer"
                    title="Clear selection" aria-label="Clear selection">
                <i class="fas fa-eraser cursor-pointer"></i></span>
                {% if not form.product_name.value %}<span>
                    <a data-form-url="{% url 'products:add_color'%}"
                    class="create-new text-green pointer" title="Add new color"
                    aria-label="Add new color">
                    <i class="fas fa-plus"></i></a></span>
                {% endif %}</div>
                """),),
                ), css_class="form-control mb-3 bg-light",
                ),
            Div(Row(
                Column('size', css_class='col-12 col-md-11'),
                Column(HTML("""
                <div class="text-end">
                <span class="clear_size text-green pointer"
                    title="Clear selection"
                    aria-label="Clear selection">
                    <i class="fas fa-eraser"></i></span>
                {% if not form.product_name.value %}<span>
                    <a data-form-url="{% url 'products:add_size'%}"
                    class="create-new" title="Add new size"
                    aria-label="Add new product type">
                    <i class="fas fa-plus text-green pointer"></i></a></span>
                    {% endif %}</div>
                """),),
                 ), css_class="form-control mb-3 bg-light",
                ),
            Div(
                'price', css_class="w-25 text-smaller"),
            HTML("""
                {%if form.image.value %}
                    <div class="my-2">
                    <img src="{{ form.instance.image.url }}"
                    class="img-fluid" style="height: 150px;"></div>
                {% else %}
                    <p class="text-smaller"> No image</p>
                {% endif %}
                """),
            HTML('<div class="mb-5 text-smaller">{{ form.image }}</div>'),
        )


class AddRatingForm(PopRequestMixin,
                    CreateUpdateAjaxMixin,
                    forms.ModelForm):
    """Form for adding product rating"""

    class Meta:
        """Specify model and form fields"""
        model = Rating
        fields = ('user', 'product', 'rating', 'comment')

        widgets = {
            'rating': forms.RadioSelect(),
            'comment': forms.Textarea(attrs={
                'lines': '5',
                'max-width': '200px',
            })
        }


class CreateTypeForm(PopRequestMixin,
                     CreateUpdateAjaxMixin,
                     forms.ModelForm):
    """Form to create new product type."""

    class Meta:
        """Meta class specifying fields."""
        model = Type
        exclude = ('slug',)


class UpdateTypeForm(PopRequestMixin,
                     forms.ModelForm):
    """Form to create new product type."""

    class Meta:
        """Meta class specifying fields."""
        model = Type
        exclude = ('slug',)


class CreateCategoryForm(PopRequestMixin,
                         CreateUpdateAjaxMixin,
                         forms.ModelForm):
    """Form to create new product type."""

    class Meta:
        """Meta class specifying fields."""
        model = Category
        exclude = ('slug',)


class UpdateCategoryForm(PopRequestMixin,
                         forms.ModelForm):
    """Form to create new product type."""

    class Meta:
        """Meta class specifying fields."""
        model = Category
        exclude = ('slug',)


class CreateSizeForm(PopRequestMixin,
                     CreateUpdateAjaxMixin,
                     forms.ModelForm):
    """Form to create new product type."""

    class Meta:
        """Meta class specifying fields."""
        model = Size
        exclude = ('slug',)


class UpdateSizeForm(PopRequestMixin,
                     forms.ModelForm):
    """Form to create new product type."""

    class Meta:
        """Meta class specifying fields."""
        model = Size
        exclude = ('slug',)


class CreateColorForm(PopRequestMixin,
                      CreateUpdateAjaxMixin,
                      forms.ModelForm):
    """Form to create new product type."""

    class Meta:
        """Meta class specifying fields."""
        model = Color
        exclude = ('slug',)


class UpdateColorForm(PopRequestMixin,
                      forms.ModelForm):
    """Form to create new product type."""

    class Meta:
        """Meta class specifying fields."""
        model = Color
        exclude = ('slug',)

products/templates/products/includes/1_star.html
<div class="d-flex flex-row">
    <i class="fas fa-star text-yellow"></i>
</div>

products/templates/products/includes/2_stars.html
<div class="d-flex flex-row">
    <i class="fas fa-star text-yellow"></i>
    <i class="fas fa-star text-yellow"></i>
</div>

products/templates/products/includes/3_stars.html
<div class="d-flex flex-row">
    <i class="fas fa-star text-yellow"></i>
    <i class="fas fa-star text-yellow"></i>
    <i class="fas fa-star text-yellow"></i>
</div>

products/templates/products/includes/4_stars.html
<div class="d-flex flex-row">
    <i class="fas fa-star text-yellow"></i>
    <i class="fas fa-star text-yellow"></i>
    <i class="fas fa-star text-yellow"></i>
    <i class="fas fa-star text-yellow"></i>
</div>

products/templates/products/includes/filters.html
<!-- Filters and sort options -->
<div id="filters" class="offcanvas offcanvas-top mx-auto bg-light w-sm-100 w-md-75 pb-5">
    <div class="row mb-3">
    <form action="{% url 'products:products' %}" method="GET">
        <div
            class="row text-uppercase small m-2 mb-0 me-md-5 justify-content-center justify-content-md-end fw-bolder small">
            Filter / Sort
            <button type="button" class="btn-close ms-1 fw-bold text-dgreen small" data-bs-dismiss="offcanvas" 
                aria-label="Close"></button>
        </div>
        {% csrf_token %}
        <!-- Filters for LARGE SCREENS -->
        <div class="container-fluid p-3 d-none d-lg-flex flex-row">
            <!-- Select color -->
            <div class="col px-5">
                <p class="text-dgreen text-uppercase fs-6 fw-bold mb-2">Color</p>
                <div class="d-flex flex-row flex-wrap lh-2">
                    <div class="d-flex flex-row flex-wrap mt-2">
                        {% for color in color_list %}
                        <div class="circle bg-{{ color.slug }} {% if color.slug == 'white' %}border border-secondary{% endif %} me-2 mb-2">
                            <input id="id_color-lg-{{ color.slug }}" type="radio" class="color d-none" name="color"
                                value="{{ color.slug }}">
                            <label for="id_color-lg-{{ color.slug }}" class="circle"></label>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <!-- Select size -->
            <div class="col px-5">
                <p class="text-dgreen text-uppercase fs-6 fw-bold mb-2">Size</p>
                <div class="d-flex flex-row flex-wrap my-2 mb-2">
                    {% for size in size_list %}
                    <div class="size-box my-2 me-2">
                        <input id="id_size-lg-{{ size.slug }}" type="radio" class="size d-none" name="size"
                            value="{{ size.slug }}">
                        <label for="id_size-lg-{{ size.slug }}"
                            class="border size-box smaller-text">{{ size.size_short}}</label>
                    </div>
                    {% endfor %}
                </div>
            </div>
            <!-- Select category -->
            <div class="col px-5">
                <p class="text-dgreen text-uppercase fs-6 fw-bold mb-2">Category</p>
                <div class="category-selector mt-2">
                    {% for category in category_list %}
                    <div class="category">
                        <input id="id_category-lg-{{ category.slug }}" type="radio" class="d-none" name="category"
                            value="{{ category.slug }}">
                        <label for="id_category-lg-{{ category.slug }}"
                            class="dropdown-item">{{ category.friendly_name}}</label>
                    </div>
                    {% endfor %}
                </div>
            </div>
            <!-- Sorting -->
            <div class="col px-5">
                <p class="text-dgreen text-uppercase fs-6 fw-bold mb-2">Sort by...</p>

                    <!-- Price ascending -->
                <div class="sort-type">
                    <input id="lg-price-low-first" name="sort" value="price-asc" type="radio" class="d-none">
                    <label for="lg-price-low-first" class="dropdown-item sort-type">Price (lowest
                        first)</label>
                </div>
                    <!-- Price descending -->
                <div class="sort-type">
                    <input id="lg-price-high-first" name="sort" value="price-desc" type="radio" class="d-none">
                    <label for="lg-price-high-first" class="dropdown-item sort-type">Price (highest
                        first)</label>
                </div>
                <!-- Name ascending -->
                <div class="sort-type">
                    <input id="lg-name-a-z" name="sort" value="name-asc" type="radio" class="d-none">
                    <label for="lg-name-a-z" class="dropdown-item sort-type">Name (A-Z)</label>
                </div>
                <!-- Name descending -->
                <div class="sort-type">
                    <input id="lg-name-z-a" name="sort" value="name-desc" type="radio" class="d-none">
                    <label for="lg-name-z-a" class="dropdown-item sort-type">Name (Z-A)</label>
                </div>
            </div>
        </div>
        <!-- Filters for SMALL SCREENS/MOBILES -->
        <div id="filters-small"
            class="container-fluid p-3 px-md-5 d-sm-block d-md-block d-lg-none justify-content-center">
            <!-- Select color -->
            <div class="col my-2">
                <a class="text-dgreen text-uppercase undecorated fs-6 fw-bold mb-3" data-bs-toggle="collapse"
                    href="#colors">Color</a>
                <div id="colors" class="collapse">
                    <div class="d-flex flex-row flex-wrap">
                        <div class="color d-flex flex-row flex-wrap mt-2">
                            {% for color in color_list %}
                            <div class="circle bg-{{ color.slug }} {% if color.slug == 'white' %}border border-secondary{% endif %} me-2 mb-1">
                                <input id="id_color-{{ color.slug }}" type="radio" class="color d-none"
                                    name="color" value="{{ color.slug }}">
                                <label for="id_color-{{ color.slug }}" class="circle"></label>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
            <!-- Select size -->
            <div class="col my-2">
                <a class="text-dgreen text-uppercase undecorated fs-6 fw-bold mb-3" data-bs-toggle="collapse"
                    href="#size">Size</a>
                <div id="size" class="collapse">
                    <div class="d-flex flex-row flex-wrap my-2">
                        {% for size in size_list %}
                        <div class="size-box my-2 me-2">
                            <input id="id_size-{{ size.slug }}" type="radio" class="size d-none" name="size"
                                value="{{ size.slug }}">
                            <label for="id_size-{{ size.slug }}"
                                class="border size-box smaller-text">{{ size.size_short}}</label>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <!-- Select category -->
            <div class="col my-2">
                <a class="text-dgreen text-uppercase undecorated fs-6 fw-bold mb-2" data-bs-toggle="collapse"
                    href="#category">Category</a>
                <div id="category" class="collapse">
                    {% for category in category_list %}
                    <div class="category w-50">
                        <input id="id_category-{{ category.slug }}" type="radio" class="d-none" name="category"
                            value="{{ category.slug }}">
                        <label for="id_category-{{ category.slug }}"
                            class="dropdown-item">{{ category.friendly_name}}</label>
                    </div>
                    {% endfor %}
                </div>
            </div>
            <!-- Sorting -->
            <div class="col my-2">
                <a class="text-dgreen text-uppercase undecorated fs-6 fw-bold mb-2" data-bs-toggle="collapse"
                    href="#sort">Sort by...</a>
                <div id="sort" class="collapse">
                    <!-- Rating -->
                    <div class="sort-type w-50">
                        <input id="rating" name="sorting" value="rating" type="radio" class="d-none">
                        <label for="rating" class="dropdown-item">Rating</label>
                    </div>
                    <!-- Price ascending -->
                    <div class="sort-type w-50">
                        <input id="price-low-first" name="sorting" value="price-low-first" type="radio" class="d-none">
                        <label for="price-low-first" class="dropdown-item">Price (lowest
                            first)</label>
                    </div>
                    <!-- Price descending -->
                    <div class="sort-type w-50">
                        <input id="price-high-first" name="sorting" value="price-high-first" type="radio" class="d-none">
                        <label for="price-high-first" class="dropdown-item">Price (highest
                            first)</label>
                    </div>
                    <!-- Name ascending -->
                    <div class="sort-type w-50">
                        <input id="name-a-z" name="sorting" value="name-a-z" type="radio" class="d-none">
                        <label for="name-a-z" class="dropdown-item">Name (A-Z)</label>
                    </div>
                    <!-- Name descending -->
                    <div class="sort-type w-50">
                        <input id="name-z-a" name="sorting" value="name-z-a" type="radio" class="d-none">
                        <label for="name-z-a" class="dropdown-item">Name (Z-A)</label>
                    </div>
                </div>
            </div>
        </div>
        <div id="filter-controls" class="text-center">
            <button id="clear-filters" class="btn main-btn-2 me-2">Clear filter</button>
            <button class="btn main-btn-1 mx-auto" type="submit">Apply filters</button>
        </div>
    </form>
    </div>
</div>

products/templates/products/includes/product_ratings.html
<div class="container-fluid mt-4">
    <h4 class="">What our clients say about <strong>{{ product.product_name }}</strong></h4>
    <div class="mb-5">
        {% for rated_product, userlist in all_rev_users.items %}
            {% if rated_product == product %}
                {% if request.user in userlist %}
                You already rated this product 
                {% else %}
                <a {% if request.user.is_authenticated %}data-form-url="{% url 'products:add_rating' product.pk %}"{% else %}href="{% url 'account_login' %}"{% endif %} class="add-rating undecorated text-dgreen link-text" title="Rate this product" aria-label="Rate product">Rate this product{% endif %}</a>
            {% endif %}
        {% endfor %}
    </div>
    <!-- Show latest 3 reviews -->
    {% for rated_product, ratings in latest_product_ratings.items %}
        {% if rated_product.pk == product.pk %}
            {% if ratings %}
                {% for rating in ratings %}
                <div class="small">
                    <div class="d-flex flex-row">
                        <p class="me-3">User: {{ rating.user }}</p>
                            {% if rating.rating == 5 %}
                                {% include 'products/includes/5_stars.html' %}
                            {% elif rating.rating == 4 %}
                                {% include 'products/includes/4_stars.html' %}
                            {% elif rating.rating == 3 %}
                                {% include 'products/includes/3_stars.html' %}
                            {% elif rating.rating == 2 %}
                                {% include 'products/includes/2_stars.html' %}
                            {% else %}
                                {% include 'products/includes/1_star.html' %}
                            {% endif %}
                    </div>
                    <div>{% if rating.comment %}
                        Comment: {{ rating.comment }}
                        {% endif %}
                    </div>
                </div>
                <hr class="w-50">
                {% endfor %}
                
            {% else %}
                <div class="mb-5">No ratings yet, be the first to 
                        <a {% if request.user.is_authenticated %}data-form-url="{% url 'products:add_rating' product.pk %}"{% else %}href="{% url 'account_login' %}"{% endif %} class="add-rating undecorated text-dgreen link-text" title="Rate this product" aria-label="Rate product">rate this product</a>
                </div>
            {% endif %}
        {% endif %}
    {% endfor %}
    <!-- Show all remaining reviews -->
    {% for rated_product, ratings in older_product_ratings.items %}
        {% if rated_product.pk == product.pk %}
            {% if ratings %}
            <div class="older_ratings mb-5 small">
                <a id="show-reviews" class="btn main-btn-2" data-bs-toggle="collapse" href="#collapseMoreRatings" role="button" aria-expanded="false" aria-controls="collapseMoreRatings" aria-label="Show more ratings">
                    Show more...</a>
                <div class="collapse mt-3" id="collapseMoreRatings">
                {% for rating in ratings %}
                <div>
                    <div class="d-flex flex-row">
                        <p class="me-3">User: {{ rating.user }}</p>
                            {% if rating.rating == 5 %}
                                <span class="small">{% include 'products/includes/5_stars.html' %}</span>
                            {% elif rating.rating == 4 %}
                                <span class="small">{% include 'products/includes/4_stars.html' %}</span>
                            {% elif rating.rating == 3 %}
                                <span class="small">{% include 'products/includes/3_stars.html' %}</span>
                            {% elif rating.rating == 2 %}
                                <span class="small">{% include 'products/includes/2_stars.html' %}</span>
                            {% else %}
                                <span class="small">{% include 'products/includes/1_star.html' %}</span>
                            {% endif %}
                    </div>
                    <div>{% if rating.comment %}
                        Comment: {{ rating.comment }}
                        {% endif %}
                    </div>
                </div>
                <hr class="w-50">
                {% endfor %}
            {% endif %}
        {% endif %}
    {% endfor %}  
</div>