bag/urls.py
"""Urls for bag app"""
from django.urls import path
from bag import views


app_name = 'bag'
urlpatterns = [
    path('', views.ViewBag.as_view(), name='view_bag'),
    path('add/<int:item_id>/', views.add_to_bag, name='add_to_bag'),
    path('adjust/<int:item_id>/', views.adjust_bag, name='adjust_bag'),
    path('remove_item/<int:item_id>/', views.remove_item, name='remove_item'),
]

green_bean/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('profile/', include('profiles.urls')),
    path('bag/', include('bag.urls')),
    path('checkout/', include('checkout.urls')),
    path('robots.txt', TemplateView.as_view(
        template_name="robots.txt", content_type="text/plain"),
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'home.views.error_404'
handler500 = 'home.views.error_500'

home/urls.py
"""Home app urls"""
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
]

products/urls.py
"""Urls for products app"""
from django.urls import path
from products import views

app_name = 'products'
urlpatterns = [
    path('', views.ProductListView.as_view(), name='products'),
    path('product_details/<int:pk>/', views.ProductDetailView.as_view(),
         name='product_details'),
    path('add/', views.CreateProductView.as_view(), name='add_product'),
    path('product_details/<int:pk>/update/', views.UpdateProductView.as_view(),
         name='edit_product'),
    path('product_details/<int:pk>/delete/', views.DeleteProductView.as_view(),
         name='delete_product'),
    path('product_details/<int:pk>/add_rating/', views.RateProduct.as_view(),
         name='add_rating'),
    # Type
    path('create_type/', views.CreateTypeView.as_view(),
         name='create_type'),
    path('add/add_type/', views.AddType.as_view(),
         name='add_type'),
    path('update_type/<int:pk>/', views.UpdateTypeView.as_view(),
         name='update_type'),
    path('delete_type/<int:pk>/', views.DeleteTypeView.as_view(),
         name='delete_type'),
    # Category
    path('create_category/', views.CreateCategoryView.as_view(),
         name='create_category'),
    path('add/add_category/', views.AddCategory.as_view(),
         name='add_category'),
    path('update_category/<int:pk>/', views.UpdateCategoryView.as_view(),
         name='update_category'),
    path('delete_category/<int:pk>/', views.DeleteCategoryView.as_view(),
         name='delete_category'),
    # Color
    path('create_color/', views.CreateColorView.as_view(),
         name='create_color'),
    path('add/add_color/', views.AddColor.as_view(),
         name='add_color'),
    path('update_color/<int:pk>/', views.UpdateColorView.as_view(),
         name='update_color'),
    path('delete_color/<int:pk>/', views.DeleteColorView.as_view(),
         name='delete_color'),
    # Size
    path('create_size/', views.CreateSizeView.as_view(),
         name='create_size'),
    path('add/add_size/', views.AddSize.as_view(),
         name='add_size'),
    path('update_size/<int:pk>/', views.UpdateSizeView.as_view(),
         name='update_size'),
    path('delete_size/<int:pk>/', views.DeleteSizeView.as_view(),
         name='delete_size'),

    path('manage_products', views.ManageProductsView.as_view(),
         name='manage_products')

]

products/models.py
"""Models for products app"""
import random
from django.contrib.auth.models import User
from django.db import models
from django.template.defaultfilters import slugify
from cloudinary.models import CloudinaryField


class Type(models.Model):
    """Create instance of Type"""
    product_type = models.CharField(max_length=100)
    type_code = models.CharField(max_length=5)
    slug = models. SlugField(max_length=100, unique=True)

    def save(self, *args, **kwargs):
        """
        Override the save method to set the product_type as slug
        """
        self.slug = slugify(self.product_type)
        super().save(*args, **kwargs)

    def __str__(self):
        """String method for type"""
        return self.product_type


class Size(models.Model):
    """Create instance of Size"""
    size_short = models.CharField(max_length=25)  # e.g. 'M'
    size_long = models.CharField(max_length=50)  # e.g. 'Medium'
    slug = models. SlugField(max_length=25, unique=True)

    def save(self, *args, **kwargs):
        """
        Override the save method to set the size_short as slug
        """
        self.slug = slugify(self.size_short)
        super().save(*args, **kwargs)

    def __str__(self):
        """String method for size"""
        return f'{self.size_long} ({self.size_short})'


class Color(models.Model):
    """Create instance of Color"""
    color = models.CharField(max_length=100)  # display color
    color_code = models.CharField(max_length=5)
    slug = models. SlugField(max_length=100, unique=True)

    def save(self, *args, **kwargs):
        """
        Override the save method to set the color as slug
        """
        self.slug = slugify(self.color)
        super().save(*args, **kwargs)

    def __str__(self):
        """String method for color"""
        return self.color


class Category(models.Model):
    """Create instance of Category"""
    category_name = models.CharField(max_length=200)
    friendly_name = models.CharField(max_length=254, null=True, blank=True)
    slug = models. SlugField(max_length=200, unique=True)

    def save(self, *args, **kwargs):
        """
        Override the save method to set the category_name as slug
        """
        self.slug = slugify(self.category_name)
        super().save(*args, **kwargs)

    class Meta:
        """Meta options for Product model"""
        verbose_name_plural = "categories"

    def get_friendly_name(self):
        """Friendly name for product category"""
        return self.friendly_name

    def __str__(self):
        """String method for category"""
        return self.category_name


class Product(models.Model):
    """Create product instance"""
    product_name = models.CharField(max_length=300)
    description = models.TextField()
    code = models.CharField(
            max_length=8,
            blank=True,
            editable=False,
            unique=True,
        )
    product_type = models.ForeignKey(
        Type, null=True, on_delete=models.SET_NULL)
    image = CloudinaryField('image', blank=True)
    category = models.ManyToManyField(Category, related_name='categories')
    size = models.ManyToManyField(Size, blank=True, related_name='sizes')
    color = models.ManyToManyField(Color, blank=True, related_name='colors')
    price = models.DecimalField(max_digits=6, decimal_places=2, null=True,
                                blank=True, default=00.00)

    def get_sizes(self):
        """Get all sizes for a product"""
        sizes = []
        for size in self.size.all():
            sizes.append(size)
        return sizes

    def get_colors(self):
        """Get all colors for a product"""
        colors = []
        for color in self.color.all():
            colors.append(color)
        return colors

    def get_categories(self):
        """Get list of categories for a product"""
        categories = []
        for category in self.category.all():
            categories.append(category)
        return categories

    def _generate_code(self):
        """Generate random number to use in the SKU and check for uniqueness"""
        code = random.randint(10000, 99999)
        products = Product.objects.all()
        codes = [product.code for product in products]

        while code in codes:
            new_code = random.randint(10000, 99999)
            code = new_code
            break
        return code

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the sku number
        if it hasn't been set already.
        """
        if not self.code:
            self.code = self._generate_code()
        super().save(*args, **kwargs)

    def __str__(self):
        """String method for product"""
        return self.product_name


class Rating(models.Model):
    """Create instance of rating"""
    RATING = (
        (1, 'Poor'),
        (2, 'Ok'),
        (3, 'Good'),
        (4, 'Very good'),
        (5, 'Excellent'),
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE,
                                related_name='rating')
    rating = models.IntegerField(default=0, choices=RATING)
    comment = models.TextField(max_length=1500)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """String method for rating"""
        return f'{self.product.product_name}_{self.rating}'

templates/includes/filters.html
<!-- Filters and sort options -->
<div id="filters" class="offcanvas offcanvas-top mx-auto bg-light w-sm-100 w-md-75" >
    <div class="row mb-3">
    <form action="{% url 'products:products' %}" method="GET">
        <div
            class="row text-uppercase small m-2 mb-0 me-5 justify-content-center justify-content-md-end fw-bolder small">
            Filter / Sort
            <small type="button" class="btn-close ms-1 mt-1 fw-bold text-dgreen" data-bs-dismiss="offcanvas"
                aria-label="Close"></small>
        </div>
        {% csrf_token %}
        <!-- Filters for LARGE SCREENS -->
        <div class="container-fluid p-3 d-none d-lg-flex flex-row">
            <!-- Select color -->
            <div class="col px-5">
                <p class="text-dgreen text-uppercase fs-6 fw-bold mb-2">Color</p>
                <div class="d-flex flex-row flex-wrap lh-2">
                    <div class="d-flex flex-row flex-wrap mt-2">
                        {% for color in color_list %}
                        <div class="circle bg-{{ color.slug }} me-2 mb-2">
                            <input id="id_color-lg-{{ color.slug }}" type="radio" class="color d-none" name="color"
                                value="{{ color.slug }}">
                            <label for="id_color-lg-{{ color.slug }}" class="circle"></label>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <!-- Select size -->
            <div class="col px-5">
                <p class="text-dgreen text-uppercase fs-6 fw-bold mb-2">Size</p>
                <div class="d-flex flex-row flex-wrap my-2 mb-2">
                    {% for size in size_list %}
                    <div class="size-box my-2 me-2">
                        <input id="id_size-lg-{{ size.slug }}" type="radio" class="size d-none" name="size"
                            value="{{ size.slug }}">
                        <label for="id_size-lg-{{ size.slug }}"
                            class="border size-box smaller-text">{{ size.size_short}}</label>
                    </div>
                    {% endfor %}
                </div>
            </div>
            <!-- Select category -->
            <div class="col px-5">
                <p class="text-dgreen text-uppercase fs-6 fw-bold mb-2">Category</p>
                <div class="category-selector mt-2">
                    {% for category in category_list %}
                    <div class="category">
                        <input id="id_category-lg-{{ category.slug }}" type="radio" class="d-none" name="category"
                            value="{{ category.slug }}">
                        <label for="id_category-lg-{{ category.slug }}"
                            class="dropdown-item">{{ category.friendly_name}}</label>
                    </div>
                    {% endfor %}
                </div>
            </div>
            <!-- Sorting -->
            <div class="col px-5">
                <p class="text-dgreen text-uppercase fs-6 fw-bold mb-2">Sort by...</p>
                <!-- Rating -->
                <div class="sort-type">
                    <input id="lg-rating" name="sort" value="rating" type="radio" class="d-none">
                    <label for="lg-rating" class="dropdown-item sort-type">Rating</label>
                </div>
                    <!-- Price ascending -->
                <div class="sort-type">
                    <input id="lg-price-low-first" name="sort" value="price-asc" type="radio" class="d-none">
                    <label for="lg-price-low-first" class="dropdown-item sort-type">Price (lowest
                        first)</label>
                </div>
                    <!-- Price descending -->
                <div class="sort-type">
                    <input id="lg-price-high-first" name="sort" value="price-desc" type="radio" class="d-none">
                    <label for="lg-price-high-first" class="dropdown-item sort-type">Price (highest
                        first)</label>
                </div>
                <!-- Name ascending -->
                <div class="sort-type">
                    <input id="lg-name-a-z" name="sort" value="name-asc" type="radio" class="d-none">
                    <label for="lg-name-a-z" class="dropdown-item sort-type">Name (A-Z)</label>
                </div>
                <!-- Name descending -->
                <div class="sort-type">
                    <input id="lg-name-z-a" name="sort" value="name-desc" type="radio" class="d-none">
                    <label for="lg-name-z-a" class="dropdown-item sort-type">Name (Z-A)</label>
                </div>
            </div>
        </div>
        <!-- Filters for SMALL SCREENS/MOBILES -->
        <div id="filters-small"
            class="container-fluid p-3 px-md-5 d-sm-block d-md-block d-lg-none justify-content-center">
            <!-- Select color -->
            <div class="col my-2">
                <a class="text-dgreen text-uppercase undecorated fs-6 fw-bold mb-3" data-bs-toggle="collapse"
                    href="#colors">Color</a>
                <div id="colors" class="collapse">
                    <div class="d-flex flex-row flex-wrap">
                        <div class="color d-flex flex-row flex-wrap mt-2">
                            {% for color in color_list %}
                            <div class="circle bg-{{ color.slug }} me-2">
                                <input id="id_color-{{ color.slug }}" type="radio" class="color d-none"
                                    name="color" value="{{ color.slug }}">
                                <label for="id_color-{{ color.slug }}" class="circle"></label>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
            <!-- Select size -->
            <div class="col my-2">
                <a class="text-dgreen text-uppercase undecorated fs-6 fw-bold mb-3" data-bs-toggle="collapse"
                    href="#size">Size</a>
                <div id="size" class="collapse">
                    <div class="d-flex flex-row flex-wrap my-2">
                        {% for size in size_list %}
                        <div class="size-box my-2 me-2">
                            <input id="id_size-{{ size.slug }}" type="radio" class="size d-none" name="size"
                                value="{{ size.slug }}">
                            <label for="id_size-{{ size.slug }}"
                                class="border size-box smaller-text">{{ size.size_short}}</label>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <!-- Select category -->
            <div class="col my-2">
                <a class="text-dgreen text-uppercase undecorated fs-6 fw-bold mb-2" data-bs-toggle="collapse"
                    href="#category">Category</a>
                <div id="category" class="collapse">
                    {% for category in category_list %}
                    <div class="category w-50">
                        <input id="id_category-{{ category.slug }}" type="radio" class="d-none" name="category"
                            value="{{ category.slug }}">
                        <label for="id_category-{{ category.slug }}"
                            class="dropdown-item">{{ category.friendly_name}}</label>
                    </div>
                    {% endfor %}
                </div>
            </div>
            <!-- Sorting -->
            <div class="col my-2">
                <p class="text-dgreen text-uppercase undecorated fs-6 fw-bold mb-2" data-bs-toggle="collapse"
                    href="#sort">Sort by...</p>
                <div id="sort" class="collapse">
                    <!-- Rating -->
                    <div class="sort-type w-50">
                        <input id="rating" name="sorting" value="rating" type="radio" class="d-none">
                        <label for="rating" class="dropdown-item">Rating</label>
                    </div>
                    <!-- Price ascending -->
                    <div class="sort-type w-50">
                        <input id="price-low-first" name="sorting" value="price-low-first" type="radio" class="d-none">
                        <label for="price-low-first" class="dropdown-item">Price (lowest
                            first)</label>
                    </div>
                    <!-- Price descending -->
                    <div class="sort-type w-50">
                        <input id="price-high-first" name="sorting" value="price-high-first" type="radio" class="d-none">
                        <label for="price-high-first" class="dropdown-item">Price (highest
                            first)</label>
                    </div>
                    <!-- Name ascending -->
                    <div class="sort-type w-50">
                        <input id="name-a-z" name="sorting" value="name-a-z" type="radio" class="d-none">
                        <label for="name-a-z" class="dropdown-item">Name (A-Z)</label>
                    </div>
                    <!-- Name descending -->
                    <div class="sort-type w-50">
                        <input id="name-z-a" name="sorting" value="name-z-a" type="radio" class="d-none">
                        <label for="name-z-a" class="dropdown-item">Name (Z-A)</label>
                    </div>
                </div>
            </div>
        </div>
        <div id="filter-controls" class="text-center">
            <button id="clear-filters" class="main-btn-2 me-2">Clear filter</button>
            <button class="main-btn-1 mx-auto" type="submit">Apply filters</button>
        </div>
    </form>
    </div>
</div>

templates/includes/main-nav.html
<div class="collapse navbar-collapse text-dgreen" id="main-nav">
    <div class="container-fluid">
        <ul class="navbar-nav w-auto mx-auto small text-uppercase">
            <!-- <li class="nav-item menu-text d-block d-md-none"> -->
            <li class="nav-item menu-text d-block">
                <a class="font-weight-bold nav-link text-black mr-5" href="{% url 'products:products' %}"
                    id="home-link">
                    All products
                </a>
            </li>
            <!-- <li class="nav-item dropdown"> -->
                <!-- <a class="font-weight-bold nav-link menu-text mr-5 me-2" href="#" id="all-products-link"
                    data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Sort by...
                </a>
                <div class="dropdown-menu border-0" aria-labelledby="all-products-link">
                    <a href="{% url 'products:products' %}?sort=price&direction=desc" class="dropdown-item">
                        Price (high to low)</a>
                    <a href="{% url 'products:products' %}?sort=price&direction=asc" class="dropdown-item">
                        Price (low to high)</a>
                    <a href="{% url 'products:products' %}?sort=product_name&direction=asc" class="dropdown-item">
                        Name</a>   
                    <a href="{% url 'products:products' %}?sort=rating&direction=asc" class="dropdown-item">
                        Rating</a> -->
                    <!-- <a href="{% url 'products:products' %}?sort=category&direction=asc" class="dropdown-item">
                        Category</a> -->
                    <!-- <a href="{% url 'products:products' %}" class="dropdown-item">All</a> -->
                <!-- </div> -->
            <!-- </li> -->
           
            <li class="nav-item dropdown">
                <a class="font-weight-bold nav-link menu-text mr-5" href="#" id="tshirts-link"
                    data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    T-shirts
                </a>
                <div class="dropdown-menu border-0" aria-labelledby="tshirts-link">
                    <a href="{% url 'products:products' %}?category=new" class="dropdown-item">New
                        Arrivals</a>
                    <a href="{% url 'products:products' %}?category=abstract" class="dropdown-item">Abstract</a>
                    <a href="{% url 'products:products' %}?category=nature" class="dropdown-item">Nature</a>
                    <a href="{% url 'products:products' %}?category=anime" class="dropdown-item">Anime</a>
                    <a href="{% url 'products:products' %}?category=new,abstract,nature,anime"
                        class="dropdown-item">Collections</a>
                </div>
            </li>

            <li class="nav-item dropdown">
                <a class="font-weight-bold nav-link menu-text mr-5" href="#" id="clothing-link"
                    data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Other
                </a>
                <div class="dropdown-menu border-0" aria-labelledby="clothing-link">
                    <a href="{% url 'products:products' %}?category=bracelets" class="dropdown-item">Bracelets</a>
                    <a href="{% url 'products:products' %}?category=accessories" class="dropdown-item">Accessories</a>
                    <a href="{% url 'products:products' %}?category=artwork" class="dropdown-item">Artwork</a>
                        class="dropdown-item">Collections</a> -->
                </div>
            </li>

            <li class="nav-item dropdown">
                <a class="font-weight-bold nav-link menu-text" href="#" id="specials-link"
                    data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Special Offers
                </a>
                <div class="dropdown-menu border-0" aria-labelledby="specials-link">
                    <a href="{% url 'products:products' %}?category=specials" class="dropdown-item">Specials</a>
                    <a href="{% url 'products:products' %}?category=clearance" class="dropdown-item">Clearance</a>
                    <a href="{% url 'products:products' %}?category=specials,clearance" class="dropdown-item">All
                        Special Offers</a>
                </div>
            </li>
        </ul>
    </div>
</div>

templates/includes/main_nav.html
<div class="collapse navbar-collapse text-dgreen" id="main-nav">
    <div class="container-fluid">
        <ul class="navbar-nav w-auto mx-auto small text-uppercase">
            <!-- <li class="nav-item menu-text d-block d-md-none"> -->
            <li class="nav-item d-block">
                <a class="nav-link mr-5 menu-text border-bottom border-secondary" href="{% url 'products:products' %}"
                    id="home-link">
                    All products
                </a>
            </li>           
            <li class="nav-item dropdown">
                <a class="nav-link menu-text mr-5" href="#" id="tshirts-link"
                    data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    T-shirts
                </a>
                <div class="dropdown-menu border-0 shadow bg-lgreen" aria-labelledby="tshirts-link">
                    <a href="{% url 'products:products' %}?category=new" class="dropdown-item">New
                        Arrivals</a>
                    <a href="{% url 'products:products' %}?category=abstract" class="dropdown-item">Abstract</a>
                    <a href="{% url 'products:products' %}?category=nature" class="dropdown-item">Nature</a>
                    <a href="{% url 'products:products' %}?category=anime" class="dropdown-item">Anime</a>
                    <a href="{% url 'products:products' %}?typet-shirt"
                        class="dropdown-item">All T-shirts</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="font-weight-bold nav-link menu-text mr-5" href="#" id="clothing-link"
                    data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Accessories
                </a>
                <div class="dropdown-menu border-0 shadow bg-lgreen" aria-labelledby="clothing-link">
                    <a href="{% url 'products:products' %}?type=bracelet" class="dropdown-item">Bracelets</a>
                    <a href="{% url 'products:products' %}?type=necklace" class="dropdown-item">Necklaces</a>
                    <a href="{% url 'products:products' %}?type=other" class="dropdown-item">Other</a>
                    <a href="{% url 'products:products' %}?type=bracelet,accessory,necklace"
                        class="dropdown-item">All Accessories</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="font-weight-bold nav-link menu-text" href="#" id="specials-link"
                    data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Special Offers
                </a>
                <div class="dropdown-menu border-0 shadow bg-lgreen mb-2" aria-labelledby="specials-link">
                    <a href="{% url 'products:products' %}?category=specials" class="dropdown-item">Specials</a>
                    <a href="{% url 'products:products' %}?category=clearance" class="dropdown-item">Clearance</a>
                    <a href="{% url 'products:products' %}?category=specials,clearance" class="dropdown-item">All
                        Special Offers</a>
                </div>
            </li>
        {% if request.user.is_superuser %}
            <li class="nav-item dropdown">
                <a class="nav-link menu-text" href="{% url 'products:manage_products' %}" id="manage-products-link">| Manage products</a>
            </li>  
        {% endif %}
        </ul>
    </div>
</div>

templates/includes/mobile-nav.html
<a href="{% url 'home:home'%}" class="nav-link main-logo-link">
    <h2 class="logo-text d-block d-lg-none my-0 mx-0 ">GreenBean</h2>
</a>
<!-- Search bar and shopping basket div-->
<div class="row d-block d-lg-none">
    <div class="d-flex flex-row justify-content-end align-items-center">
        <!-- Search button -->
        <div class="col fs-5">
            <a data-bs-toggle="offcanvas" href="#searchBar" role="button"
            aria-expanded="false" aria-controls="searchBarBtn"><i class="fas fa-search icon"></i></a>
        </div>
        <!-- Shopping basket -->
        <div id="shopping-cart" class="col my-auto py-1 py-lg-0">
            <a class="nav-link {% if grand_total %}fw-bold{% else %}{% endif %}"
                href="{% url 'bag:view_bag' %}">
                <div class="text-end">
                    <div class="position-relative">
                        <div class="position-absolute top-0 start-100 translate-middle bag-item-counter mt-1 me-2"">
                        <!-- <div class="bag-item-counter"> -->
                           {{ product_count }}
                        </div>
                    <i class="fas fa-shopping-bag fa-lg icon me-2"></i>
                    <p class="my-0 icon">
                        {% if total %}
                        £{{ total|floatformat:2 }}
                        {% else %}
                        £0.00
                        {% endif %}
                    </p>
                    </div>
                </div>
            </a>
        </div>
    </div>
</div>

templates/includes/mobile_nav.html
<a href="{% url 'home:home'%}" class="nav-link main-logo-link">
    <h2 class="logo-text d-block d-lg-none my-0 mx-0 ">GreenBean</h2>
</a>
<!-- Search bar and shopping basket div-->
<div class="d-block d-lg-none">
    <div class="d-flex flex-row justify-content-end align-items-center">
        <!-- Search button -->
        <div class="col fs-5">
            <a data-bs-toggle="offcanvas" href="#searchBar" role="button"
            aria-expanded="false" aria-controls="searchBarBtn"><i class="fas fa-search icon"></i></a>
        </div>
        <!-- Shopping basket -->
        <div id="shopping-cart-mob" class="col my-auto py-1 py-lg-0 pe-1 pe-md-3">
            <a class="nav-link {% if grand_total %}fw-bold{% else %}{% endif %}"
                href="{% url 'bag:view_bag' %}">
                <div class="text-end">
                    <div class="position-relative">
                        <div class="position-absolute top-0 start-100 translate-middle bag-item-counter mt-1 me-2">
                        <!-- <div class="bag-item-counter"> -->
                           {{ product_count }}
                        </div>
                    <i class="fas fa-shopping-bag fa-lg icon me-2"></i>
                    <p class="my-0 icon">
                        {% if total %}
                        £{{ total|floatformat:2 }}
                        {% else %}
                        £0.00
                        {% endif %}
                    </p>
                    </div>
                </div>
            </a>
        </div>
    </div>
</div>

templates/includes/search-bar-popup.html
<div class="offcanvas offcanvas-top" id="searchBar">
    <div class="container-fluid my-auto mt-4">
        <div class="m-auto py-lg-0 search-bar bg-light w-100">
            <form method="GET" action="{% url 'products:products' %}">
                <div class="d-flex flex-row">
                    <input class="flex-grow-1 mx-auto ms-2 search-input py-1" type="text" name="q" placeholder="Search">
                    <span class="me-2 ">
                        <button class="form-group-text rounded-0 pe-2" type="submit">
                            <i class="fas fa-search icon"></i>
                        </button>
                    </span>
                </div>
            </form>
        </div>
    </div>
</div>