bag/urls.py
"""Urls for bag app"""
from django.urls import path
from bag import views


app_name = 'bag'
urlpatterns = [
    path('', views.ViewBag.as_view(), name='view_bag'),
    path('add/<int:item_id>/', views.add_to_bag, name='add_to_bag'),
    path('adjust/<int:item_id>/', views.adjust_bag, name='adjust_bag'),
    path('remove_item/<int:item_id>/', views.remove_item, name='remove_item'),
]

green_bean/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('profile/', include('profiles.urls')),
    path('bag/', include('bag.urls')),
    path('checkout/', include('checkout.urls')),
    path('robots.txt', TemplateView.as_view(
        template_name="robots.txt", content_type="text/plain"),
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'home.views.error_404'
handler500 = 'home.views.error_500'

products/urls.py
"""Urls for products app"""
from django.urls import path
from products import views

app_name = 'products'
urlpatterns = [
    path('', views.ProductListView.as_view(), name='products'),
    path('product_details/<int:pk>/', views.ProductDetailView.as_view(),
         name='product_details'),
    path('add/', views.CreateProductView.as_view(), name='add_product'),
    path('product_details/<int:pk>/update/', views.UpdateProductView.as_view(),
         name='edit_product'),
    path('product_details/<int:pk>/delete/', views.DeleteProductView.as_view(),
         name='delete_product'),
    path('product_details/<int:pk>/add_rating/', views.RateProduct.as_view(),
         name='add_rating'),
    # Type
    path('create_type/', views.CreateTypeView.as_view(),
         name='create_type'),
    path('add/add_type/', views.AddType.as_view(),
         name='add_type'),
    path('update_type/<int:pk>/', views.UpdateTypeView.as_view(),
         name='update_type'),
    path('delete_type/<int:pk>/', views.DeleteTypeView.as_view(),
         name='delete_type'),
    # Category
    path('create_category/', views.CreateCategoryView.as_view(),
         name='create_category'),
    path('add/add_category/', views.AddCategory.as_view(),
         name='add_category'),
    path('update_category/<int:pk>/', views.UpdateCategoryView.as_view(),
         name='update_category'),
    path('delete_category/<int:pk>/', views.DeleteCategoryView.as_view(),
         name='delete_category'),
    # Color
    path('create_color/', views.CreateColorView.as_view(),
         name='create_color'),
    path('add/add_color/', views.AddColor.as_view(),
         name='add_color'),
    path('update_color/<int:pk>/', views.UpdateColorView.as_view(),
         name='update_color'),
    path('delete_color/<int:pk>/', views.DeleteColorView.as_view(),
         name='delete_color'),
    # Size
    path('create_size/', views.CreateSizeView.as_view(),
         name='create_size'),
    path('add/add_size/', views.AddSize.as_view(),
         name='add_size'),
    path('update_size/<int:pk>/', views.UpdateSizeView.as_view(),
         name='update_size'),
    path('delete_size/<int:pk>/', views.DeleteSizeView.as_view(),
         name='delete_size'),

    path('manage_products', views.ManageProductsView.as_view(),
         name='manage_products')

]

products/models.py
"""Models for products app"""
import random
from django.contrib.auth.models import User
from django.db import models
from django.template.defaultfilters import slugify
from cloudinary.models import CloudinaryField


class Type(models.Model):
    """Create instance of Type"""
    product_type = models.CharField(max_length=100)
    type_code = models.CharField(max_length=5)
    slug = models. SlugField(max_length=100, unique=True)

    def save(self, *args, **kwargs):
        """
        Override the save method to set the product_type as slug
        """
        self.slug = slugify(self.product_type)
        super().save(*args, **kwargs)

    def __str__(self):
        """String method for type"""
        return self.product_type


class Size(models.Model):
    """Create instance of Size"""
    size_short = models.CharField(max_length=25)  # e.g. 'M'
    size_long = models.CharField(max_length=50)  # e.g. 'Medium'
    slug = models. SlugField(max_length=25, unique=True)

    def save(self, *args, **kwargs):
        """
        Override the save method to set the size_short as slug
        """
        self.slug = slugify(self.size_short)
        super().save(*args, **kwargs)

    def __str__(self):
        """String method for size"""
        return f'{self.size_long} ({self.size_short})'


class Color(models.Model):
    """Create instance of Color"""
    color = models.CharField(max_length=100)  # display color
    color_code = models.CharField(max_length=5)
    slug = models. SlugField(max_length=100, unique=True)

    def save(self, *args, **kwargs):
        """
        Override the save method to set the color as slug
        """
        self.slug = slugify(self.color)
        super().save(*args, **kwargs)

    def __str__(self):
        """String method for color"""
        return self.color


class Category(models.Model):
    """Create instance of Category"""
    category_name = models.CharField(max_length=200)
    friendly_name = models.CharField(max_length=254, null=True, blank=True)
    slug = models. SlugField(max_length=200, unique=True)

    def save(self, *args, **kwargs):
        """
        Override the save method to set the category_name as slug
        """
        self.slug = slugify(self.category_name)
        super().save(*args, **kwargs)

    class Meta:
        """Meta options for Product model"""
        verbose_name_plural = "categories"

    def get_friendly_name(self):
        """Friendly name for product category"""
        return self.friendly_name

    def __str__(self):
        """String method for category"""
        return self.category_name


class Product(models.Model):
    """Create product instance"""
    product_name = models.CharField(max_length=300)
    description = models.TextField()
    code = models.CharField(
            max_length=8,
            blank=True,
            editable=False,
            unique=True,
        )
    product_type = models.ForeignKey(
        Type, null=True, on_delete=models.SET_NULL)
    image = CloudinaryField('image', blank=True)
    category = models.ManyToManyField(Category, related_name='categories')
    size = models.ManyToManyField(Size, blank=True, related_name='sizes')
    color = models.ManyToManyField(Color, blank=True, related_name='colors')
    price = models.DecimalField(max_digits=6, decimal_places=2, null=True,
                                blank=True, default=00.00)

    def get_sizes(self):
        """Get all sizes for a product"""
        sizes = []
        for size in self.size.all():
            sizes.append(size)
        return sizes

    def get_colors(self):
        """Get all colors for a product"""
        colors = []
        for color in self.color.all():
            colors.append(color)
        return colors

    def get_categories(self):
        """Get list of categories for a product"""
        categories = []
        for category in self.category.all():
            categories.append(category)
        return categories

    def _generate_code(self):
        """Generate random number to use in the SKU and check for uniqueness"""
        code = random.randint(10000, 99999)
        products = Product.objects.all()
        codes = [product.code for product in products]

        while code in codes:
            new_code = random.randint(10000, 99999)
            code = new_code
            break
        return code

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the sku number
        if it hasn't been set already.
        """
        if not self.code:
            self.code = self._generate_code()
        super().save(*args, **kwargs)

    def __str__(self):
        """String method for product"""
        return self.product_name


class Rating(models.Model):
    """Create instance of rating"""
    RATING = (
        (1, 'Poor'),
        (2, 'Ok'),
        (3, 'Good'),
        (4, 'Very good'),
        (5, 'Excellent'),
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE,
                                related_name='rating')
    rating = models.IntegerField(default=0, choices=RATING)
    comment = models.TextField(max_length=1500)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """String method for rating"""
        return f'{self.product.product_name}_{self.rating}'

products/forms.py
"""Forms for Product view"""
from django import forms
from bootstrap_modal_forms.mixins import (
    PopRequestMixin,
    CreateUpdateAjaxMixin
)
from crispy_forms.helper import FormHelper
from crispy_forms.layout import (
    Layout,
    HTML,
    Field,
    Div,
    Row,
    Column
)
from .models import (
    Product,
    Category,
    Color,
    Type,
    Size,
    Rating,
)


class CreateProductForm(forms.ModelForm):
    """Form to create new product."""

    class Meta:
        """Meta class specifying fields."""
        model = Product
        exclude = ('slug',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        categories = Category.objects.all()
        friendly_names = [(c.id, c.get_friendly_name()) for c in categories]
        self.fields['category'].choices = friendly_names

        self.helper = FormHelper(self)
        self.helper.form_tag = False
        self.helper.disable_csrf = True
        self.helper.layout = Layout(
            Div('product_name', css_class="col-12 col-md-11 form-control\
                mb-3 bg-light"),
            Field('description', css_class="col-12 col-md-11\
                form-control mb-3 bg-light", rows="3", ),
            Div(Row(
                Column('product_type', css_class="col-12 col-md-11"),
                Column(HTML("""
                {% if not form.product_name.value %}
                    <div class="text-end"><span>
                    <a data-form-url="{% url 'products:add_type'%}"
                        class="create-new pointer" title="Add new product type"
                        aria-label="Add new product type">
                    <i class="fas fa-plus text-green pointer"></i></a>
                    </span></div>
                {% endif %}
                """),),
                ), css_class="form-control mb-3 bg-light",),
            Div(Row(
                Column('category', css_class='col-12 col-md-11'),
                Column(HTML("""
                    <div class="text-end">
                    <span class="clear_category text-green pointer"
                        title="Clear selection" aria-label="Clear selection">
                        <i class="fas fa-eraser"></i></span>
                    {% if not form.product_name.value %}<span>
                        <a data-form-url="{% url 'products:add_category'%}"
                        class="create-new text-green pointer"
                        title="Add new product
                        type" aria-label="Add new product type">
                        <i class="fas fa-plus"></i></a></span>
                    {% endif %}</div>
                """),),
                ), css_class="form-control mb-3 bg-light",),
            Div(Row(
                Column('color', css_class='col-12 col-md-11'),
                Column(HTML("""
                <div class="text-end">
                <span class="clear_color text-green pointer"
                    title="Clear selection" aria-label="Clear selection">
                <i class="fas fa-eraser cursor-pointer"></i></span>
                {% if not form.product_name.value %}<span>
                    <a data-form-url="{% url 'products:add_color'%}"
                    class="create-new text-green pointer" title="Add new color"
                    aria-label="Add new color">
                    <i class="fas fa-plus"></i></a></span>
                {% endif %}</div>
                """),),
                ), css_class="form-control mb-3 bg-light",
                ),
            Div(Row(
                Column('size', css_class='col-12 col-md-11'),
                Column(HTML("""
                <div class="text-end">
                <span class="clear_size text-green pointer"
                    title="Clear selection"
                    aria-label="Clear selection">
                    <i class="fas fa-eraser"></i></span>
                {% if not form.product_name.value %}<span>
                    <a data-form-url="{% url 'products:add_size'%}"
                    class="create-new" title="Add new size"
                    aria-label="Add new product type">
                    <i class="fas fa-plus text-green pointer"></i></a></span>
                    {% endif %}</div>
                """),),
                 ), css_class="form-control mb-3 bg-light",
                ),
            Div(
                'price', css_class="w-25 text-smaller"),
            HTML("""
                {%if form.image.value %}
                    <div class="my-2">
                    <img src="{{ form.instance.image.url }}"
                    class="img-fluid" style="height: 150px;"></div>
                {% else %}
                    <p class="text-smaller"> No image</p>
                {% endif %}
                """),
            HTML('<div class="mb-5 text-smaller">{{ form.image }}</div>'),
        )


class AddRatingForm(PopRequestMixin,
                    CreateUpdateAjaxMixin,
                    forms.ModelForm):
    """Form for adding product rating"""

    class Meta:
        """Specify model and form fields"""
        model = Rating
        fields = ('user', 'product', 'rating', 'comment')

        widgets = {
            'rating': forms.RadioSelect(),
            'comment': forms.Textarea(attrs={
                'lines': '5',
                'max-width': '200px',
            })
        }


class CreateTypeForm(PopRequestMixin,
                     CreateUpdateAjaxMixin,
                     forms.ModelForm):
    """Form to create new product type."""

    class Meta:
        """Meta class specifying fields."""
        model = Type
        exclude = ('slug',)


class UpdateTypeForm(PopRequestMixin,
                     forms.ModelForm):
    """Form to create new product type."""

    class Meta:
        """Meta class specifying fields."""
        model = Type
        exclude = ('slug',)


class CreateCategoryForm(PopRequestMixin,
                         CreateUpdateAjaxMixin,
                         forms.ModelForm):
    """Form to create new product type."""

    class Meta:
        """Meta class specifying fields."""
        model = Category
        exclude = ('slug',)


class UpdateCategoryForm(PopRequestMixin,
                         forms.ModelForm):
    """Form to create new product type."""

    class Meta:
        """Meta class specifying fields."""
        model = Category
        exclude = ('slug',)


class CreateSizeForm(PopRequestMixin,
                     CreateUpdateAjaxMixin,
                     forms.ModelForm):
    """Form to create new product type."""

    class Meta:
        """Meta class specifying fields."""
        model = Size
        exclude = ('slug',)


class UpdateSizeForm(PopRequestMixin,
                     forms.ModelForm):
    """Form to create new product type."""

    class Meta:
        """Meta class specifying fields."""
        model = Size
        exclude = ('slug',)


class CreateColorForm(PopRequestMixin,
                      CreateUpdateAjaxMixin,
                      forms.ModelForm):
    """Form to create new product type."""

    class Meta:
        """Meta class specifying fields."""
        model = Color
        exclude = ('slug',)


class UpdateColorForm(PopRequestMixin,
                      forms.ModelForm):
    """Form to create new product type."""

    class Meta:
        """Meta class specifying fields."""
        model = Color
        exclude = ('slug',)

products/templates/products/delete.html
<form method="post">
    {% csrf_token %}
    <!-- Modal content injected into the modal div in the main manage categories view  -->
    <div class="modal-header">
      <h3 class="modal-title">
        {% if product %}
        Delete product?
        {% elif type %}
        Delete type?
        {% elif category %}
        Delete category?
        {% elif color %}
        Delete color?
        {% else %}
        Delete size?
        {% endif %}
      </h3>
      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>
  
    <div class="modal-body">
      <p>Are you sure you want to delete <strong>{{ product.name }}</strong>? This action cannot be undone.</p>
    </div>
  
    <div class="modal-footer">
      <button type="submit" class="btn">Delete</button>
    </div>
</form>

products/templates/products/edit_product.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% crispy example_form example_form.helper %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'products/css/products.css' %}">
{% endblock %}
{% block page_header %}

<div class="container p-4 p-lg-5 pb-0">
        <h2 class="text-dgreen">Manage products</h2>
        <h3 class="text-secondary">Edit product</h3>
    <hr>
</div>
{% endblock %}

{% block content %}
<div class="container">
    <div class="row offset-md-1">
        <div class="col-12 col-md-9">
            <form method="POST" class="form mb-2" enctype="multipart/form-data">
                {% csrf_token %}
                {% crispy form %}
                <div class="modal-footer m-auto mt-5">
                    <div class="m-auto">
                        <a href="{% url 'products:products' %}" class="btn main-btn-2">Cancel</a>
                        <button type="submit" class="btn main-btn-1" aria-label="Save">Save</button>
                    </div>
                </div>
            </form>
        </div>            
    </div>
    <div class="d-flex justify-content-between mb-3">
        <a href="{% url 'products:manage_products' %}" class="btn main-btn-2 fw-bold small">&lt;&lt; Back to <u>Manage products</u></a>
        <a href="{% url 'products:products' %}" class="btn main-btn-2 fw-bold small">&lt;&lt; Back to <u>All products</u></a>
    </div>
</div>
{% endblock %}

{% block postloadjs %}
    {{ block.super }}
        <script src="{% static 'products/js/products.js' %}"></script>
        <script src="{% static 'products/js/bs_modal_forms.js' %}"></script>
{% endblock %}

products/templates/products/manage_products.html
{% extends 'base.html' %}
{% load static %}


{% block page_header %}
<div class="container p-4 p-lg-5 pb-0 pb-lg-1">
    <div class="row">
        <h3 class="col text-dgreen">Manage products</h3>
    </div>
    <hr>
</div>
{% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'products/css/products.css' %}">
{% endblock %}

{% block content %}
<div class="container px-4 px-lg-5">
    <div class="accordion accordion-flush" id="accordionProductMangement">
        <!-- Products -->
        <div class="accordion-item">
            <div class="d-flex flex-row align-items-center justify-content-end">
                <h2 class="accordion-header flex-grow-1" id="flush-headingOne">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                        data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
                        Products
                    </button>
                </h2>
                <div><a href="{% url 'products:add_product' %}" type="button" class="btn main-btn-1 small py-0">Add new</a>
                </div>
            </div>
            <div id="flush-collapseOne" class="accordion-collapse collapse" aria-labelledby="flush-headingOne"
                data-bs-parent="#accordionProductMangement">
                <div class="accordion-body">
                    <table class="table table-responsive table-hover">
                        <thead>
                            <tr>
                                <th>Product</th>
                                <th>Type</th>
                                <th class="text-center">Preview</th>
                                <th class="text-center">Delete</th>
                            </tr>
                        </thead>
                        <tbody class="small">
                            {% for product in products %}
                            <tr>
                                <td><a href="{% url 'products:edit_product' product.pk %}" class="undecorated link-text">{{ product }}</a></td>
                                <td>{{ product.product_type }}</td>
                                <td class="text-center"><a href="{% url 'products:product_details' product.pk %}"><i
                                            class="fas fa-eye text-green"></i></a></td>
                                <td class="text-center"><a type="button" class="delete bs-modal"
                                        data-form-url="{% url 'products:delete_product' product.pk %}"><i
                                            class="far fa-trash-alt text-green"></i></a></td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <!-- Categories -->
        <div class="accordion-item">
            <div class="d-flex flex-row align-items-center justify-content-end">
                <h2 class="accordion-header flex-grow-1" id="flush-headingTwo">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                        data-bs-target="#flush-collapseTwo" aria-expanded="false" aria-controls="flush-collapseTwo">
                       Categories
                    </button>
                </h2>
                <div><a data-form-url="{% url 'products:create_category' %}" type="button" class="create-new btn main-btn-1 py-0 small">Add new</a></div>
            </div>
            <div id="flush-collapseTwo" class="accordion-collapse collapse" aria-labelledby="flush-headingTwo"
                data-bs-parent="#accordionProductMangement">
                <div class="accordion-body">
                    <table class="table table-responsive table-hover">
                        <thead>
                            <tr>
                                <th>Friendly name</th>
                                <!-- <th></th> -->
                                <th class="text-center">Edit</th>
                                <th class="text-center">Delete</th>
                            </tr>
                        </thead>
                        <tbody class="small">
                            {% for category in categories %}
                            <tr>
                                <td>{{ category.friendly_name }}</td>
                                <!-- <td>{{ product.product_type }}</td> -->
                                <td class="text-center"><a
                                        data-form-url="{% url 'products:update_category' category.pk %}" class="edit"><i
                                            class="fas fa-pen text-green"></i></a></td>
                                <td class="text-center"><a type="button" class="delete bs-modal"
                                        data-form-url="{% url 'products:delete_category' category.pk %}"><i
                                            class="far fa-trash-alt text-green"></i></a></td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <!-- Types -->
        <div class="accordion-item">
            <div class="d-flex flex-row align-items-center justify-content-end">
            <h2 class="accordion-header flex-grow-1" id="flush-headingThree">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                    data-bs-target="#flush-collapseThree" aria-expanded="false" aria-controls="flush-collapseThree">
                    Product Types
                </button>
            </h2>
            <div><a data-form-url="{% url 'products:create_type' %}" type="button" class="create-new btn main-btn-1 py-0 small">Add new</a></div>
            </div>
            <div id="flush-collapseThree" class="accordion-collapse collapse" aria-labelledby="flush-headingThree"
                data-bs-parent="#accordionProductMangement">
                <div class="accordion-body">
                    <table class="table table-responsive table-hover">
                        <thead>
                            <tr>
                                <th>Type</th>
                                <th>Code</th>
                                <th class="text-center">Edit</th>
                                <th class="text-center">Delete</th>
                            </tr>
                        </thead>
                        <tbody class="small">
                            {% for type in types %}
                            <tr>
                                <td>{{ type.product_type }}</td>
                                <td>{{ type.type_code }}</td>
                                <td class="text-center"><a
                                        data-form-url="{% url 'products:update_type' type.pk %}" class="edit"><i
                                            class="fas fa-pen text-green"></i></a></td>
                                <td class="text-center"><a type="button" class="delete bs-modal"
                                        data-form-url="{% url 'products:delete_type' type.pk %}"><i
                                            class="far fa-trash-alt text-green"></i></a></td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <!-- Colors -->
        <div class="accordion-item">
            <div class="d-flex flex-row align-items-center justify-content-end">
            <h2 class="accordion-header flex-grow-1" id="flush-headingThree">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                    data-bs-target="#flush-collapseFour" aria-expanded="false" aria-controls="flush-collapseFour">
                    Colors
                </button>
            </h2>
            <div><a data-form-url="{% url 'products:create_color' %}" type="button" class="create-new btn main-btn-1 py-0 small">Add new</a></div>
            </div>
            <div id="flush-collapseFour" class="accordion-collapse collapse" aria-labelledby="flush-headingFour"
                data-bs-parent="#accordionProductMangement">
                <div class="accordion-body">
                    <table class="table table-responsive table-hover">
                        <thead>
                            <tr>
                                <th>Color</th>
                                <th>Code</th>
                                <th class="text-center">Edit</th>
                                <th class="text-center">Delete</th>
                            </tr>
                        </thead>
                        <tbody class="small">
                            {% for color in colors %}
                            <tr>
                                <td>{{ color.color }}</td>
                                <td>{{ color.color_code }}</td>
                                <td class="text-center"><a
                                        data-form-url="{% url 'products:update_color' color.pk %}" class="edit"><i
                                            class="fas fa-pen text-green"></i></a></td>
                                <td class="text-center"><a type="button" class="delete bs-modal"
                                        data-form-url="{% url 'products:delete_color' color.pk %}"><i
                                            class="far fa-trash-alt text-green"></i></a></td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
            <!-- Sizes -->
        <div class="accordion-item">
            <div class="d-flex flex-row align-items-center justify-content-end">
            <h2 class="accordion-header flex-grow-1" id="flush-headingThree">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                    data-bs-target="#flush-collapseFive" aria-expanded="false" aria-controls="flush-collapseFive">
                    Sizes
                </button>
            </h2>
            <div><a data-form-url="{% url 'products:create_size' %}" type="button" class="create-new btn main-btn-1 py-0 small">Add new</a></div>
            </div>
            <div id="flush-collapseFive" class="accordion-collapse collapse" aria-labelledby="flush-headingFive"
                data-bs-parent="#accordionProductMangement">
                <div class="accordion-body">
                    <table class="table table-responsive table-hover">
                        <thead>
                            <tr>
                                <th>Size</th>
                                <th>Size short</th>
                                <th class="text-center">Edit</th>
                                <th class="text-center">Delete</th>
                            </tr>
                        </thead>
                        <tbody class="small">
                            {% for size in sizes %}
                            <tr>
                                <td>{{ size.size_long }}</td>
                                <td>{{ size.size_short }}</td>
                                <td class="text-center"><a
                                        data-form-url="{% url 'products:update_size' size.pk %}" class="edit"><i
                                            class="fas fa-pen text-green"></i></a></td>
                                <td class="text-center"><a type="button" class="delete bs-modal"
                                        data-form-url="{% url 'products:delete_size' size.pk %}"><i
                                            class="far fa-trash-alt text-green"></i></a></td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block postloadjs %}
{{ block.super }}
{% include 'products/includes/quantity_input_script.html' %}
<!-- <script src="{% static 'products/js/products.js' %}"></script> -->
<script src="{% static 'products/js/bs_modal_forms.js' %}"></script>
{% endblock %}